import uuid
from codecs import CodecInfo
from typing import AnyStr
from typing_extensions import final

class CodecContext:
    def get_text_codec(self) -> CodecInfo: ...
    def is_encoding_utf8(self) -> bool: ...
    def get_json_decoder(self) -> object: ...
    def is_decoding_json(self) -> bool: ...
    def get_json_encoder(self) -> object: ...
    def is_encoding_json(self) -> bool: ...

@final
class ReadBuffer: ...

@final
class WriteBuffer: ...

class BufferError(Exception): ...

@final
class UUID(uuid.UUID):
    def __init__(self, inp: AnyStr) -> None: ...
