from asyncio import AbstractEventLoop, Task
from os import PathLike
from pathlib import Path
from typing import Any, AnyStr, overload

PY_36: bool
PY_37: bool
SYSTEM: str

def aiter_compat(func: Any) -> Any: ...
@overload
def fspath(path: str) -> str: ...
@overload
def fspath(path: bytes) -> bytes: ...
@overload
def fspath(path: PathLike[AnyStr]) -> Any: ...
def get_pg_home_directory() -> Path: ...
def current_asyncio_task(loop: AbstractEventLoop) -> Task[Any]: ...
