from collections.abc import Iterator
from typing import Any, final, overload
from typing_extensions import Self, TypeVar

_T = TypeVar('_T')
_Record = TypeVar('_Record', bound=Record, default=Record)

class Record:
    @overload
    def get(self, key: str) -> Any | None: ...
    @overload
    def get(self, key: str, default: _T) -> Any | _T: ...
    def items(self) -> Iterator[tuple[str, Any]]: ...
    def keys(self) -> Iterator[str]: ...
    def values(self) -> Iterator[Any]: ...
    @overload
    def __getitem__(self, index: str) -> Any: ...
    @overload
    def __getitem__(self, index: int) -> Any: ...
    @overload
    def __getitem__(self, index: slice) -> tuple[Any, ...]: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __contains__(self, x: object) -> bool: ...
    def __len__(self) -> int: ...

@final
class RecordDescriptor:
    def make_record(self, desc_type: type[_Record], size: int) -> _Record: ...

@final
class RecordItemsIterator(Iterator[tuple[str, Any]]):
    def __length_hint__(self) -> int: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> tuple[str, Any]: ...

@final
class RecordIterator(Iterator[Any]):
    def __length_hint__(self) -> int: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> Any: ...
